services:
  pokevision_web:
    image: node:20-alpine
    container_name: pokevision_web
    working_dir: /app
    volumes:
      - ./:/app
      - /root/Golbat/ReactMap/server/src/configs:/external-configs
    environment:
      PORT: "5000"
      DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1416732634943328306/1gYG99jBzkRomBjkseLqANRbktIPLpx9wNWc8GyqreRTQKXVvTkUxhWjfrglKpfg1Bkb"  # set yours
      LOCAL_CONFIG_PATH: "/external-configs/local.json"
      LOCAL_CONFIG_SYNC_ENABLED: "true"
    command: >
      sh -lc "
      npm ci --include=dev &&
      npm run build &&
      npm run start
      "
    ports:
      - "127.0.0.1:5000:5000"
    restart: unless-stopped
    networks:
      - npm

networks:
  npm:
    external: true
    name: nginx_atlas-network
